<?xml version="1.0" encoding="UTF-8"?>
<wavelist version="2">
  <insertion-point-position>33</insertion-point-position>
  <wave>
    <expr>clock</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.dbus_ack</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.dbus_adr</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.dbus_cyc</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.dbus_dat</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.dbus_rdt</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.dbus_sel</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.dbus_we</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.ibus_ack</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.ibus_adr</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.ibus_cyc</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.ibus_rdt</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.reset</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_halt</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_insn</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_intr</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_mem_addr</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_mem_rdata</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_mem_rmask</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_mem_wdata</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_mem_wmask</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_mode</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_order</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_pc_rdata</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_pc_wdata</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_rd_addr</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_rd_wdata</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_rs1_addr</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_rs1_rdata</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_rs2_addr</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_rs2_rdata</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_trap</expr>
    <label/>
    <radix/>
  </wave>
  <wave>
    <expr>wrapper.rvfi_valid</expr>
    <label/>
    <radix/>
  </wave>
</wavelist>
