rvfi_insn_add.v 
rvfi_insn_addi.v 
rvfi_insn_and.v 
rvfi_insn_andi.v 
rvfi_insn_beq.v
rvfi_insn_bne.v
rvfi_insn_auipc.v
rvfi_insn_bge.v
rvfi_insn_bgeu.v
rvfi_insn_blt.v
rvfi_insn_bltu.v
rvfi_insn_jal.v
rvfi_insn_jalr.v
rvfi_insn_lb.v
rvfi_insn_lbu.v
rvfi_insn_lh.v
rvfi_insn_lhu.v
rvfi_insn_lui.v
rvfi_insn_lw.v
rvfi_insn_or.v
rvfi_insn_ori.v
rvfi_insn_sb.v
rvfi_insn_sh.v
rvfi_insn_sll.v
rvfi_insn_slli.v
rvfi_insn_slt.v
rvfi_insn_slti.v
rvfi_insn_sltiu.v
rvfi_insn_sltu.v
rvfi_insn_sra.v
rvfi_insn_srai.v
rvfi_insn_srl.v
rvfi_insn_srli.v
rvfi_insn_sub.v
rvfi_insn_sw.v
rvfi_insn_xor.v
rvfi_insn_xori.v
rvfi_isa_rv32i.v
rvfi_insn_check.sv  
rvfi_testbench.sv  
rvfi_wrapper.sv 
jg_define.sv 
rvfi_macros.vh
rvfi_insn_div.v
rvfi_insn_divu.v
rvfi_insn_mul.v
rvfi_insn_mulh.v
rvfi_insn_mulhu.v
rvfi_insn_mulhsu.v
rvfi_insn_rem.v
rvfi_insn_remu.v
insn_c_add.v
insn_c_addi.v
insn_c_addi4spn.v
insn_c_addi16sp.v
insn_c_and.v
insn_c_andi.v
insn_c_beqz.v
insn_c_bnez.v
insn_c_j.v
insn_c_jal.v
insn_c_jalr.v
insn_c_jr.v
insn_c_li.v
insn_c_lui.v
insn_c_lw.v
insn_c_lwsp.v
insn_c_mv.v
insn_c_or.v
insn_c_slli.v
insn_c_srai.v
insn_c_srli.v
insn_c_sub.v
insn_c_sw.v
insn_c_swsp.v
insn_c_xor.v
rvfi_causal_check.sv
rvfi_liveness_check.sv
rvfi_pc_fwd_check.sv
rvfi_pc_bwd_check.sv
rvfi_reg_check.sv
rvfi_unique_check.sv

